<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<AssemblyName>CESMII.OpcUa.NodeSetValidator</AssemblyName>
		<RootNamespace>CESMII.OpcUa.NodeSetValidator</RootNamespace>
		<PackageId>CESMII.OpcUa.NodeSetValidator</PackageId>
    <Version>2.1.2</Version>
    <Authors>Chris Muench</Authors>
		<Company>CESMII/C-Labs</Company>
		<Product>OPC UA NodeSet Validator</Product>
    <Copyright>Copyright © 2022-2024 CESMII. All rights reserved.</Copyright>
    <ProjectName>$(AssemblyName).$(TargetFramework)</ProjectName>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<LangVersion>latest</LangVersion>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.374.78" />
		<PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Symbols" Version="1.5.374.78" />
		<PackageReference Include="System.Text.Json" Version="6.0.4" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\CESMII.OpcUa.CloudLibraryResolver\CESMII.OpcUa.CloudLibraryResolver.csproj" />
	  <ProjectReference Include="..\CESMII.OpcUa.NodeSetImporter\CESMII.OpcUa.NodeSetImporter.csproj" />
	</ItemGroup>


</Project>
